accordion-padding = 0
after-login-command = []
after-startup-command = []
automatically-unhide-macos-hidden-apps = false
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = 'move-mouse monitor-lazy-center'
start-at-login = true

[workspace-to-monitor-force-assignment]
1 = ['main', 'secondary']
2 = ['main', 'secondary']
3 = ['main', 'secondary']
4 = ['main', 'secondary']
5 = ['main', 'secondary']
6 = ['main', 'secondary']
7 = ['main', 'secondary']
8 = ['main', 'secondary']
9 = ['main', 'secondary']

A = ['secondary', 'main']
B = ['secondary', 'main']
C = ['secondary', 'main']
D = ['secondary', 'main']
E = ['secondary', 'main']
F = ['secondary', 'main']
G = ['secondary', 'main']

[gaps]
inner.horizontal = 2
inner.vertical =   2
outer.left =       2
outer.bottom =     2
outer.top =        2
outer.right =      2

[mode.main.binding]
alt-shift-ctrl-cmd-minus = 'resize smart -100'
alt-shift-ctrl-cmd-backspace = 'close-all-windows-but-current'
alt-shift-ctrl-cmd-equal = 'resize smart +100'

alt-shift-ctrl-cmd-0 = 'balance-sizes'
alt-shift-ctrl-cmd-a = 'layout accordion horizontal vertical'
alt-shift-ctrl-cmd-c = 'reload-config'
alt-shift-ctrl-cmd-f = 'layout floating tiling'
alt-shift-ctrl-cmd-r = 'flatten-workspace-tree'
alt-shift-ctrl-cmd-t = 'layout tiles vertical horizontal'

alt-shift-ctrl-h = 'focus left --boundaries-action wrap-around-the-workspace'
alt-shift-ctrl-j = 'focus down --boundaries-action wrap-around-the-workspace'
alt-shift-ctrl-k = 'focus up --boundaries-action wrap-around-the-workspace'
alt-shift-ctrl-l = 'focus right --boundaries-action wrap-around-the-workspace'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-ctrl-cmd-h = 'join-with left'
alt-shift-ctrl-cmd-j = 'join-with down'
alt-shift-ctrl-cmd-k = 'join-with up'
alt-shift-ctrl-cmd-l = 'join-with right'

alt-shift-ctrl-1 = 'workspace 1'
alt-shift-ctrl-2 = 'workspace 2'
alt-shift-ctrl-3 = 'workspace 3'
alt-shift-ctrl-4 = 'workspace 4'
alt-shift-ctrl-5 = 'workspace 5'
alt-shift-ctrl-6 = 'workspace 6'
alt-shift-ctrl-7 = 'workspace 7'
alt-shift-ctrl-8 = 'workspace 8'
alt-shift-ctrl-9 = 'workspace 9'

alt-shift-ctrl-a = 'workspace A'
alt-shift-ctrl-b = 'workspace B'
alt-shift-ctrl-c = 'workspace C'
alt-shift-ctrl-d = 'workspace D'
alt-shift-ctrl-e = 'workspace E'
alt-shift-ctrl-f = 'workspace F'
alt-shift-ctrl-g = 'workspace G'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-shift-a = 'move-node-to-workspace A'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-f = 'move-node-to-workspace F'
alt-shift-g = 'move-node-to-workspace G'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
[mode.service.binding]
esc = ['reload-config', 'mode main']

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.install4j.0526-4458-1435-8154.837'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace A'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace A'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace C'

[[on-window-detected]]
if.app-id = 'com.apple.iWork.Numbers'
run = 'move-node-to-workspace E'
